### ISSUE TITLE
metrics issues from SDKs

### ISSUE THREAD

**Issue by puckpuck** [open-telemetry/opentelemetry-demo#1147]
Some metrics emitted by some SDKs have caused issues within the demo.  We have to write special rules in the OpenTelemetry collector to mitigate them, and even with those rules we still can experience some problems.

This is a way for us to track these issues, and when they are fixed upstream so we can implement the appropriate fixes in the demo.

- [x] `rpc.server.duration` in Go has high cardinality attributes which cause issues within the productcatalog service (ongoing today), as well as memory consumption by the collector and prometheus (mitigated with a collector filter rule). This is being tracked by this [issue in the Go SDK](https://github.com/open-telemetry/opentelemetry-go-contrib/issues/3071)
- [x] `queueSize` in the Java Agent is emitted multiple times with different attributes and descriptions. This causes an issue with the Prometheus export from the Collector (mitigated with a collector transform rule). This is being tracked by this [issue in the Java Instrumentation repo](https://github.com/open-telemetry/opentelemetry-java/issues/4834)
- [x] `rpc.server.duration` in Java and Go is using an incorrect description that does not match semantic conventions. This causes an issue with the Prometheus export from the Collector (mitigated with a collector transform rule). This is being tracked by this [issue in the Java Instrumentation repo](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/9478) and this [issue in the Go SDK](https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4301)
- [x] `http.client.duration` in Python is using an incorrect description that does not match semantic conventions. This causes an issue with the Prometheus export from the Collector (mitigated with a collector transform rule). This is being tracked by this [issue in the Python SDK](https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1958)

**Comment by austinlparker** [comment]
Is this issue still needed?
