### ISSUE TITLE
Helm updates for v1.4

### ISSUE THREAD

**Issue by puckpuck** [open-telemetry/opentelemetry-demo#777]
Tracking list of issues on the OpenTelemetry Helm chart repo for the demo to create a v1.4 release.

- [x] [Not support arm64 images bug Something isn't working](https://github.com/open-telemetry/opentelemetry-helm-charts/issues/580)
- [x] [Add support for OpenShift](https://github.com/open-telemetry/opentelemetry-helm-charts/issues/681)
- [x] [[Demo] Add support for env from secrets](https://github.com/open-telemetry/opentelemetry-helm-charts/issues/663)
- [x] [[demo] Add Security Context for all demo components](https://github.com/open-telemetry/opentelemetry-helm-charts/issues/665)
- [x] [[demo] startup order/dependency for components](https://github.com/open-telemetry/opentelemetry-helm-charts/issues/666)
- [x] [[demo] add LivenessProbe and SecurityContext to values schema](https://github.com/open-telemetry/opentelemetry-helm-charts/issues/667)
- [x] [[demo] add more CI tests and examples](https://github.com/open-telemetry/opentelemetry-helm-charts/issues/668)

**Comment by puckpuck** [comment]
Adding SecurityContext to each pod is based on challenges for getting the demo to work in OpenShift. Those 2 tasks are related to each other.

Is anyone aware of a free OpenShift cluster we can use to do some testing? I would need kubectl/helm access to the cluster.

**Comment by puckpuck** [comment]
OpenShift, by default, is quite restrictive, and any of our services that specify a `USER` in the Dockerfile will fail to start. The Demo has several services with this specified, which is done for various reasons. I see 2 options we can take to overcome this.

**Option 1:**
OpenShift Security Context Constraints (SCC) can be applied to the Demo service account to enable the Demo to start up and work. Enabling these capabilities requires a user with elevated permissions in OpenShift. Once set, the Demo can be installed by a standard developer user with all other restrictions. We need to add some minor changes to our Helm chart for the `frontend` and `paymentservice` as well to work in this method.

For this option, we need to make the required changes to the Helm chart for `frontend` and `paymentservice`, and include additional instructions for an OpenShift administrator to run the proper `oc adm policy add-scc-to-user ...` commands to apply the appropriate SCC, to allow a developer to install the Demo.

**Option 2**
We need to modify the Dockerfile for each service that specifies `USER`, and allow the service to startup by any non-root user, which OpenShift will assign when it starts the container. This may require doing additional permission changes in the Dockerfile. We also need to remove the `securityContext` definition on each service in Helm since OpenShift will control that aspect for each container/pod. The services that specify `USER` in the Dockerfile are: `frontend`, `frontendProxy`, `paymentservice`, `quoteservice`, `ffs-postgres`, `kafka`, and `redis`.


**Recommendation**
Of the 2 options, the second option contains significantly more effort and risk. As such, I recommend we do **Option 1**. This isn't ideal since it still requires an OpenShift Administrator to enable some permissions. Still, it will allow us to provide an option for people in OpenShift to use the Demo. I still see a future where we have this work without requiring administrator assistance, just not for the upcoming 1.4 release.

**Comment by puckpuck** [comment]
[This PR](https://github.com/open-telemetry/opentelemetry-helm-charts/pull/729) in the Helm charts repo implements Option 1 above
